-- 1. SERIES
CREATE TABLE SERIES (
    serie_id varchar(10) PRIMARY KEY,
    serie_name varchar(50) NOT NULL
);

-- 2. CIRCUITS
CREATE TABLE CIRCUITS (
    circuit_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    circuit_slug varchar(50) UNIQUE NOT NULL,
    circuit_name varchar(100) NOT NULL,
    circuit_locality varchar(100),
    circuit_country varchar(100),
    circuit_latitude double precision,
    circuit_longitude double precision,
    circuit_external_id varchar(100)
);

-- 3. TEAMS
CREATE TABLE TEAMS (
    team_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    serie_id varchar(10) NOT NULL,
    team_name varchar(100) NOT NULL,
    team_external_id varchar(100),
    CONSTRAINT teams_series_fk FOREIGN KEY (serie_id) REFERENCES SERIES(serie_id)
);

-- 4. DRIVERS
CREATE TABLE DRIVERS (
    driver_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    serie_id varchar(10) NOT NULL,
    team_id int,
    driver_first_name varchar(50) NOT NULL,
    driver_last_name varchar(50) NOT NULL,
    driver_code varchar(5),
    driver_number int,
    driver_external_id varchar(100),
    CONSTRAINT drivers_series_fk FOREIGN KEY (serie_id) REFERENCES SERIES(serie_id),
    CONSTRAINT drivers_teams_fk FOREIGN KEY (team_id) REFERENCES TEAMS(team_id) ON DELETE SET NULL
);

-- 5. EVENTS
CREATE TABLE EVENTS (
    event_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    serie_id varchar(10) NOT NULL,
    circuit_id int NOT NULL,
    event_season int NOT NULL,
    event_round int NOT NULL,
    event_slug varchar(100) UNIQUE NOT NULL,
    event_name varchar(100) NOT NULL,
    event_starts_at timestamp with time zone NOT NULL,
    event_status varchar(20) NOT NULL DEFAULT 'scheduled',
    event_official_url varchar(255),
    event_ticket_url varchar(255),
    event_external_id varchar(100),
    CONSTRAINT events_series_fk FOREIGN KEY (serie_id) REFERENCES SERIES(serie_id),
    CONSTRAINT events_circuits_fk FOREIGN KEY (circuit_id) REFERENCES CIRCUITS(circuit_id) ON DELETE RESTRICT,
    CONSTRAINT events_series_season_round_uk UNIQUE (serie_id, event_season, event_round),
    CONSTRAINT events_status_check CHECK (event_status IN ('scheduled', 'completed', 'cancelled', 'postponed'))
);

-- 6. SESSIONS
CREATE TABLE SESSIONS (
    session_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id int NOT NULL,
    session_kind varchar(20) NOT NULL,
    session_name varchar(50) NOT NULL,
    session_starts_at timestamp with time zone NOT NULL,
    CONSTRAINT sessions_events_fk FOREIGN KEY (event_id) REFERENCES EVENTS(event_id) ON DELETE CASCADE,
    CONSTRAINT sessions_kind_check CHECK (session_kind IN ('practice', 'qualifying', 'sprint', 'race', 'other'))
);

-- 7. RESULTS
CREATE TABLE RESULTS (
    event_id int NOT NULL,
    session_type varchar(10) NOT NULL DEFAULT 'race',
    result_position int NOT NULL,
    driver_id int NOT NULL,
    team_id int NOT NULL,
    result_time_or_gap varchar(50),
    result_points double precision,
    CONSTRAINT results_pk PRIMARY KEY (event_id, session_type, result_position),
    CONSTRAINT results_events_fk FOREIGN KEY (event_id) REFERENCES EVENTS(event_id) ON DELETE CASCADE,
    CONSTRAINT results_drivers_fk FOREIGN KEY (driver_id) REFERENCES DRIVERS(driver_id) ON DELETE RESTRICT,
    CONSTRAINT results_teams_fk FOREIGN KEY (team_id) REFERENCES TEAMS(team_id) ON DELETE RESTRICT,
    CONSTRAINT results_position_check CHECK (result_position BETWEEN 1 AND 3),
    CONSTRAINT results_session_type_check CHECK (session_type IN ('race', 'sprint'))
);

-- 8. SYNC_RUN
CREATE TABLE SYNC_RUN (
    sync_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    serie_id varchar(10) NOT NULL,
    started_at timestamp with time zone NOT NULL DEFAULT now(),
    finished_at timestamp with time zone,
    ok boolean NOT NULL DEFAULT false,
    message varchar(255),
    CONSTRAINT sync_run_serie_fk FOREIGN KEY (serie_id) REFERENCES SERIES(serie_id)
);

-- SEED DATA
INSERT INTO SERIES (serie_id, serie_name) VALUES
    ('f1', 'Formula 1'),
    ('motogp', 'MotoGP')
ON CONFLICT (serie_id) DO NOTHING;

-- INDEXES
CREATE INDEX IF NOT EXISTS idx_events_starts_at ON EVENTS(event_starts_at);
CREATE INDEX IF NOT EXISTS idx_events_series_season ON EVENTS(serie_id, event_season);
CREATE INDEX IF NOT EXISTS idx_sessions_event_starts ON SESSIONS(event_id, session_starts_at);
CREATE INDEX IF NOT EXISTS idx_results_event_session ON RESULTS(event_id, session_type);
CREATE INDEX IF NOT EXISTS idx_events_external_id ON EVENTS(serie_id, event_external_id) WHERE event_external_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_drivers_external_id ON DRIVERS(serie_id, driver_external_id) WHERE driver_external_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_teams_external_id ON TEAMS(serie_id, team_external_id) WHERE team_external_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_circuits_slug ON CIRCUITS(circuit_slug);

