// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: events.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getEventBySlug = `-- name: GetEventBySlug :one
SELECT 
    e.event_id,
    e.serie_id,
    e.circuit_id,
    e.event_season,
    e.event_round,
    e.event_slug,
    e.event_name,
    e.event_starts_at,
    e.event_status,
    e.event_official_url,
    e.event_ticket_url,
    c.circuit_slug,
    c.circuit_name,
    c.circuit_locality,
    c.circuit_country,
    c.circuit_latitude,
    c.circuit_longitude
FROM EVENTS e
JOIN CIRCUITS c ON e.circuit_id = c.circuit_id
WHERE e.event_slug = $1
`

type GetEventBySlugRow struct {
	EventID          int32              `json:"event_id"`
	SerieID          string             `json:"serie_id"`
	CircuitID        int32              `json:"circuit_id"`
	EventSeason      int32              `json:"event_season"`
	EventRound       int32              `json:"event_round"`
	EventSlug        string             `json:"event_slug"`
	EventName        string             `json:"event_name"`
	EventStartsAt    pgtype.Timestamptz `json:"event_starts_at"`
	EventStatus      string             `json:"event_status"`
	EventOfficialUrl pgtype.Text        `json:"event_official_url"`
	EventTicketUrl   pgtype.Text        `json:"event_ticket_url"`
	CircuitSlug      string             `json:"circuit_slug"`
	CircuitName      string             `json:"circuit_name"`
	CircuitLocality  pgtype.Text        `json:"circuit_locality"`
	CircuitCountry   pgtype.Text        `json:"circuit_country"`
	CircuitLatitude  pgtype.Float8      `json:"circuit_latitude"`
	CircuitLongitude pgtype.Float8      `json:"circuit_longitude"`
}

func (q *Queries) GetEventBySlug(ctx context.Context, eventSlug string) (GetEventBySlugRow, error) {
	row := q.db.QueryRow(ctx, getEventBySlug, eventSlug)
	var i GetEventBySlugRow
	err := row.Scan(
		&i.EventID,
		&i.SerieID,
		&i.CircuitID,
		&i.EventSeason,
		&i.EventRound,
		&i.EventSlug,
		&i.EventName,
		&i.EventStartsAt,
		&i.EventStatus,
		&i.EventOfficialUrl,
		&i.EventTicketUrl,
		&i.CircuitSlug,
		&i.CircuitName,
		&i.CircuitLocality,
		&i.CircuitCountry,
		&i.CircuitLatitude,
		&i.CircuitLongitude,
	)
	return i, err
}

const getLastCompletedEventBySeries = `-- name: GetLastCompletedEventBySeries :one
SELECT 
    e.event_id,
    e.serie_id,
    e.circuit_id,
    e.event_season,
    e.event_round,
    e.event_slug,
    e.event_name,
    e.event_starts_at,
    e.event_status,
    e.event_official_url,
    e.event_ticket_url,
    c.circuit_slug,
    c.circuit_name,
    c.circuit_locality,
    c.circuit_country
FROM EVENTS e
JOIN CIRCUITS c ON e.circuit_id = c.circuit_id
WHERE e.serie_id = $1 AND e.event_status = 'completed'
ORDER BY e.event_starts_at DESC
LIMIT 1
`

type GetLastCompletedEventBySeriesRow struct {
	EventID          int32              `json:"event_id"`
	SerieID          string             `json:"serie_id"`
	CircuitID        int32              `json:"circuit_id"`
	EventSeason      int32              `json:"event_season"`
	EventRound       int32              `json:"event_round"`
	EventSlug        string             `json:"event_slug"`
	EventName        string             `json:"event_name"`
	EventStartsAt    pgtype.Timestamptz `json:"event_starts_at"`
	EventStatus      string             `json:"event_status"`
	EventOfficialUrl pgtype.Text        `json:"event_official_url"`
	EventTicketUrl   pgtype.Text        `json:"event_ticket_url"`
	CircuitSlug      string             `json:"circuit_slug"`
	CircuitName      string             `json:"circuit_name"`
	CircuitLocality  pgtype.Text        `json:"circuit_locality"`
	CircuitCountry   pgtype.Text        `json:"circuit_country"`
}

func (q *Queries) GetLastCompletedEventBySeries(ctx context.Context, serieID string) (GetLastCompletedEventBySeriesRow, error) {
	row := q.db.QueryRow(ctx, getLastCompletedEventBySeries, serieID)
	var i GetLastCompletedEventBySeriesRow
	err := row.Scan(
		&i.EventID,
		&i.SerieID,
		&i.CircuitID,
		&i.EventSeason,
		&i.EventRound,
		&i.EventSlug,
		&i.EventName,
		&i.EventStartsAt,
		&i.EventStatus,
		&i.EventOfficialUrl,
		&i.EventTicketUrl,
		&i.CircuitSlug,
		&i.CircuitName,
		&i.CircuitLocality,
		&i.CircuitCountry,
	)
	return i, err
}

const listSessionsByEventID = `-- name: ListSessionsByEventID :many
SELECT 
    session_id,
    event_id,
    session_kind,
    session_name,
    session_starts_at
FROM SESSIONS
WHERE event_id = $1
ORDER BY session_starts_at ASC
`

func (q *Queries) ListSessionsByEventID(ctx context.Context, eventID int32) ([]Session, error) {
	rows, err := q.db.Query(ctx, listSessionsByEventID, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Session{}
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.SessionID,
			&i.EventID,
			&i.SessionKind,
			&i.SessionName,
			&i.SessionStartsAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUpcomingEvents = `-- name: ListUpcomingEvents :many
SELECT 
    e.event_id,
    e.serie_id,
    e.circuit_id,
    e.event_season,
    e.event_round,
    e.event_slug,
    e.event_name,
    e.event_starts_at,
    e.event_status,
    e.event_official_url,
    e.event_ticket_url,
    c.circuit_slug,
    c.circuit_name,
    c.circuit_locality,
    c.circuit_country
FROM EVENTS e
JOIN CIRCUITS c ON e.circuit_id = c.circuit_id
WHERE e.event_starts_at >= $1
ORDER BY e.event_starts_at ASC
`

type ListUpcomingEventsRow struct {
	EventID          int32              `json:"event_id"`
	SerieID          string             `json:"serie_id"`
	CircuitID        int32              `json:"circuit_id"`
	EventSeason      int32              `json:"event_season"`
	EventRound       int32              `json:"event_round"`
	EventSlug        string             `json:"event_slug"`
	EventName        string             `json:"event_name"`
	EventStartsAt    pgtype.Timestamptz `json:"event_starts_at"`
	EventStatus      string             `json:"event_status"`
	EventOfficialUrl pgtype.Text        `json:"event_official_url"`
	EventTicketUrl   pgtype.Text        `json:"event_ticket_url"`
	CircuitSlug      string             `json:"circuit_slug"`
	CircuitName      string             `json:"circuit_name"`
	CircuitLocality  pgtype.Text        `json:"circuit_locality"`
	CircuitCountry   pgtype.Text        `json:"circuit_country"`
}

func (q *Queries) ListUpcomingEvents(ctx context.Context, eventStartsAt pgtype.Timestamptz) ([]ListUpcomingEventsRow, error) {
	rows, err := q.db.Query(ctx, listUpcomingEvents, eventStartsAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUpcomingEventsRow{}
	for rows.Next() {
		var i ListUpcomingEventsRow
		if err := rows.Scan(
			&i.EventID,
			&i.SerieID,
			&i.CircuitID,
			&i.EventSeason,
			&i.EventRound,
			&i.EventSlug,
			&i.EventName,
			&i.EventStartsAt,
			&i.EventStatus,
			&i.EventOfficialUrl,
			&i.EventTicketUrl,
			&i.CircuitSlug,
			&i.CircuitName,
			&i.CircuitLocality,
			&i.CircuitCountry,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUpcomingEventsBySeries = `-- name: ListUpcomingEventsBySeries :many
SELECT 
    e.event_id,
    e.serie_id,
    e.circuit_id,
    e.event_season,
    e.event_round,
    e.event_slug,
    e.event_name,
    e.event_starts_at,
    e.event_status,
    e.event_official_url,
    e.event_ticket_url,
    c.circuit_slug,
    c.circuit_name,
    c.circuit_locality,
    c.circuit_country
FROM EVENTS e
JOIN CIRCUITS c ON e.circuit_id = c.circuit_id
WHERE e.serie_id = $1 AND e.event_starts_at >= $2
ORDER BY e.event_starts_at ASC
`

type ListUpcomingEventsBySeriesParams struct {
	SerieID       string             `json:"serie_id"`
	EventStartsAt pgtype.Timestamptz `json:"event_starts_at"`
}

type ListUpcomingEventsBySeriesRow struct {
	EventID          int32              `json:"event_id"`
	SerieID          string             `json:"serie_id"`
	CircuitID        int32              `json:"circuit_id"`
	EventSeason      int32              `json:"event_season"`
	EventRound       int32              `json:"event_round"`
	EventSlug        string             `json:"event_slug"`
	EventName        string             `json:"event_name"`
	EventStartsAt    pgtype.Timestamptz `json:"event_starts_at"`
	EventStatus      string             `json:"event_status"`
	EventOfficialUrl pgtype.Text        `json:"event_official_url"`
	EventTicketUrl   pgtype.Text        `json:"event_ticket_url"`
	CircuitSlug      string             `json:"circuit_slug"`
	CircuitName      string             `json:"circuit_name"`
	CircuitLocality  pgtype.Text        `json:"circuit_locality"`
	CircuitCountry   pgtype.Text        `json:"circuit_country"`
}

func (q *Queries) ListUpcomingEventsBySeries(ctx context.Context, arg ListUpcomingEventsBySeriesParams) ([]ListUpcomingEventsBySeriesRow, error) {
	rows, err := q.db.Query(ctx, listUpcomingEventsBySeries, arg.SerieID, arg.EventStartsAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUpcomingEventsBySeriesRow{}
	for rows.Next() {
		var i ListUpcomingEventsBySeriesRow
		if err := rows.Scan(
			&i.EventID,
			&i.SerieID,
			&i.CircuitID,
			&i.EventSeason,
			&i.EventRound,
			&i.EventSlug,
			&i.EventName,
			&i.EventStartsAt,
			&i.EventStatus,
			&i.EventOfficialUrl,
			&i.EventTicketUrl,
			&i.CircuitSlug,
			&i.CircuitName,
			&i.CircuitLocality,
			&i.CircuitCountry,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
