// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Circuit struct {
	CircuitID         int32         `json:"circuit_id"`
	CircuitSlug       string        `json:"circuit_slug"`
	CircuitName       string        `json:"circuit_name"`
	CircuitLocality   pgtype.Text   `json:"circuit_locality"`
	CircuitCountry    pgtype.Text   `json:"circuit_country"`
	CircuitLatitude   pgtype.Float8 `json:"circuit_latitude"`
	CircuitLongitude  pgtype.Float8 `json:"circuit_longitude"`
	CircuitExternalID pgtype.Text   `json:"circuit_external_id"`
}

type Driver struct {
	DriverID         int32       `json:"driver_id"`
	SerieID          string      `json:"serie_id"`
	TeamID           pgtype.Int4 `json:"team_id"`
	DriverFirstName  string      `json:"driver_first_name"`
	DriverLastName   string      `json:"driver_last_name"`
	DriverCode       pgtype.Text `json:"driver_code"`
	DriverNumber     pgtype.Int4 `json:"driver_number"`
	DriverExternalID pgtype.Text `json:"driver_external_id"`
}

type Event struct {
	EventID          int32              `json:"event_id"`
	SerieID          string             `json:"serie_id"`
	CircuitID        int32              `json:"circuit_id"`
	EventSeason      int32              `json:"event_season"`
	EventRound       int32              `json:"event_round"`
	EventSlug        string             `json:"event_slug"`
	EventName        string             `json:"event_name"`
	EventStartsAt    pgtype.Timestamptz `json:"event_starts_at"`
	EventStatus      string             `json:"event_status"`
	EventOfficialUrl pgtype.Text        `json:"event_official_url"`
	EventTicketUrl   pgtype.Text        `json:"event_ticket_url"`
	EventExternalID  pgtype.Text        `json:"event_external_id"`
}

type Result struct {
	EventID         int32         `json:"event_id"`
	SessionType     string        `json:"session_type"`
	ResultPosition  int32         `json:"result_position"`
	DriverID        int32         `json:"driver_id"`
	TeamID          int32         `json:"team_id"`
	ResultTimeOrGap pgtype.Text   `json:"result_time_or_gap"`
	ResultPoints    pgtype.Float8 `json:"result_points"`
}

type Series struct {
	SerieID   string `json:"serie_id"`
	SerieName string `json:"serie_name"`
	SerieSlug string `json:"serie_slug"`
}

type Session struct {
	SessionID       int32              `json:"session_id"`
	EventID         int32              `json:"event_id"`
	SessionKind     string             `json:"session_kind"`
	SessionName     string             `json:"session_name"`
	SessionStartsAt pgtype.Timestamptz `json:"session_starts_at"`
}

type SyncRun struct {
	SyncID     int32              `json:"sync_id"`
	SerieID    string             `json:"serie_id"`
	StartedAt  pgtype.Timestamptz `json:"started_at"`
	FinishedAt pgtype.Timestamptz `json:"finished_at"`
	Ok         bool               `json:"ok"`
	Message    pgtype.Text        `json:"message"`
}

type Team struct {
	TeamID         int32       `json:"team_id"`
	SerieID        string      `json:"serie_id"`
	TeamName       string      `json:"team_name"`
	TeamExternalID pgtype.Text `json:"team_external_id"`
}
