// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: series.sql

package db

import (
	"context"
)

const getSeries = `-- name: GetSeries :one
SELECT serie_id, serie_name, serie_slug
FROM SERIES
WHERE serie_id = $1
`

func (q *Queries) GetSeries(ctx context.Context, serieID string) (Series, error) {
	row := q.db.QueryRow(ctx, getSeries, serieID)
	var i Series
	err := row.Scan(&i.SerieID, &i.SerieName, &i.SerieSlug)
	return i, err
}

const getSeriesBySlug = `-- name: GetSeriesBySlug :one
SELECT serie_id, serie_name, serie_slug
FROM SERIES
WHERE serie_slug = $1
`

func (q *Queries) GetSeriesBySlug(ctx context.Context, serieSlug string) (Series, error) {
	row := q.db.QueryRow(ctx, getSeriesBySlug, serieSlug)
	var i Series
	err := row.Scan(&i.SerieID, &i.SerieName, &i.SerieSlug)
	return i, err
}

const listSeries = `-- name: ListSeries :many
SELECT serie_id, serie_name, serie_slug
FROM SERIES
ORDER BY serie_id ASC
`

func (q *Queries) ListSeries(ctx context.Context) ([]Series, error) {
	rows, err := q.db.Query(ctx, listSeries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Series{}
	for rows.Next() {
		var i Series
		if err := rows.Scan(&i.SerieID, &i.SerieName, &i.SerieSlug); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
