// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sync.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSyncRun = `-- name: CreateSyncRun :one
INSERT INTO SYNC_RUN (serie_id, started_at, ok, message)
VALUES ($1, now(), false, $2)
RETURNING sync_id, serie_id, started_at, finished_at, ok, message
`

type CreateSyncRunParams struct {
	SerieID string      `json:"serie_id"`
	Message pgtype.Text `json:"message"`
}

func (q *Queries) CreateSyncRun(ctx context.Context, arg CreateSyncRunParams) (SyncRun, error) {
	row := q.db.QueryRow(ctx, createSyncRun, arg.SerieID, arg.Message)
	var i SyncRun
	err := row.Scan(
		&i.SyncID,
		&i.SerieID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Ok,
		&i.Message,
	)
	return i, err
}

const deleteSessionsByEventID = `-- name: DeleteSessionsByEventID :exec
DELETE FROM SESSIONS
WHERE event_id = $1
`

func (q *Queries) DeleteSessionsByEventID(ctx context.Context, eventID int32) error {
	_, err := q.db.Exec(ctx, deleteSessionsByEventID, eventID)
	return err
}

const finishSyncRun = `-- name: FinishSyncRun :exec
UPDATE SYNC_RUN
SET finished_at = now(), ok = $2, message = $3
WHERE sync_id = $1
`

type FinishSyncRunParams struct {
	SyncID  int32       `json:"sync_id"`
	Ok      bool        `json:"ok"`
	Message pgtype.Text `json:"message"`
}

func (q *Queries) FinishSyncRun(ctx context.Context, arg FinishSyncRunParams) error {
	_, err := q.db.Exec(ctx, finishSyncRun, arg.SyncID, arg.Ok, arg.Message)
	return err
}

const getCircuitBySlug = `-- name: GetCircuitBySlug :one
SELECT circuit_id, circuit_slug, circuit_name, circuit_locality, circuit_country, circuit_latitude, circuit_longitude, circuit_external_id
FROM CIRCUITS
WHERE circuit_slug = $1
`

func (q *Queries) GetCircuitBySlug(ctx context.Context, circuitSlug string) (Circuit, error) {
	row := q.db.QueryRow(ctx, getCircuitBySlug, circuitSlug)
	var i Circuit
	err := row.Scan(
		&i.CircuitID,
		&i.CircuitSlug,
		&i.CircuitName,
		&i.CircuitLocality,
		&i.CircuitCountry,
		&i.CircuitLatitude,
		&i.CircuitLongitude,
		&i.CircuitExternalID,
	)
	return i, err
}

const getDriverByExternalID = `-- name: GetDriverByExternalID :one
SELECT driver_id, serie_id, team_id, driver_first_name, driver_last_name, driver_code, driver_number, driver_external_id
FROM DRIVERS
WHERE serie_id = $1 AND driver_external_id = $2
`

type GetDriverByExternalIDParams struct {
	SerieID          string      `json:"serie_id"`
	DriverExternalID pgtype.Text `json:"driver_external_id"`
}

func (q *Queries) GetDriverByExternalID(ctx context.Context, arg GetDriverByExternalIDParams) (Driver, error) {
	row := q.db.QueryRow(ctx, getDriverByExternalID, arg.SerieID, arg.DriverExternalID)
	var i Driver
	err := row.Scan(
		&i.DriverID,
		&i.SerieID,
		&i.TeamID,
		&i.DriverFirstName,
		&i.DriverLastName,
		&i.DriverCode,
		&i.DriverNumber,
		&i.DriverExternalID,
	)
	return i, err
}

const getLastSyncRunBySeries = `-- name: GetLastSyncRunBySeries :one
SELECT sync_id, serie_id, started_at, finished_at, ok, message
FROM SYNC_RUN
WHERE serie_id = $1
ORDER BY started_at DESC
LIMIT 1
`

func (q *Queries) GetLastSyncRunBySeries(ctx context.Context, serieID string) (SyncRun, error) {
	row := q.db.QueryRow(ctx, getLastSyncRunBySeries, serieID)
	var i SyncRun
	err := row.Scan(
		&i.SyncID,
		&i.SerieID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Ok,
		&i.Message,
	)
	return i, err
}

const getTeamByExternalID = `-- name: GetTeamByExternalID :one
SELECT team_id, serie_id, team_name, team_external_id
FROM TEAMS
WHERE serie_id = $1 AND team_external_id = $2
`

type GetTeamByExternalIDParams struct {
	SerieID        string      `json:"serie_id"`
	TeamExternalID pgtype.Text `json:"team_external_id"`
}

func (q *Queries) GetTeamByExternalID(ctx context.Context, arg GetTeamByExternalIDParams) (Team, error) {
	row := q.db.QueryRow(ctx, getTeamByExternalID, arg.SerieID, arg.TeamExternalID)
	var i Team
	err := row.Scan(
		&i.TeamID,
		&i.SerieID,
		&i.TeamName,
		&i.TeamExternalID,
	)
	return i, err
}

const getTeamByName = `-- name: GetTeamByName :one
SELECT team_id, serie_id, team_name, team_external_id
FROM TEAMS
WHERE serie_id = $1 AND team_name = $2
`

type GetTeamByNameParams struct {
	SerieID  string `json:"serie_id"`
	TeamName string `json:"team_name"`
}

func (q *Queries) GetTeamByName(ctx context.Context, arg GetTeamByNameParams) (Team, error) {
	row := q.db.QueryRow(ctx, getTeamByName, arg.SerieID, arg.TeamName)
	var i Team
	err := row.Scan(
		&i.TeamID,
		&i.SerieID,
		&i.TeamName,
		&i.TeamExternalID,
	)
	return i, err
}

const insertDriver = `-- name: InsertDriver :one
INSERT INTO DRIVERS (
    serie_id, team_id, driver_first_name, driver_last_name,
    driver_code, driver_number, driver_external_id
) VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING driver_id
`

type InsertDriverParams struct {
	SerieID          string      `json:"serie_id"`
	TeamID           pgtype.Int4 `json:"team_id"`
	DriverFirstName  string      `json:"driver_first_name"`
	DriverLastName   string      `json:"driver_last_name"`
	DriverCode       pgtype.Text `json:"driver_code"`
	DriverNumber     pgtype.Int4 `json:"driver_number"`
	DriverExternalID pgtype.Text `json:"driver_external_id"`
}

func (q *Queries) InsertDriver(ctx context.Context, arg InsertDriverParams) (int32, error) {
	row := q.db.QueryRow(ctx, insertDriver,
		arg.SerieID,
		arg.TeamID,
		arg.DriverFirstName,
		arg.DriverLastName,
		arg.DriverCode,
		arg.DriverNumber,
		arg.DriverExternalID,
	)
	var driver_id int32
	err := row.Scan(&driver_id)
	return driver_id, err
}

const insertSession = `-- name: InsertSession :one
INSERT INTO SESSIONS (event_id, session_kind, session_name, session_starts_at)
VALUES ($1, $2, $3, $4)
RETURNING session_id
`

type InsertSessionParams struct {
	EventID         int32              `json:"event_id"`
	SessionKind     string             `json:"session_kind"`
	SessionName     string             `json:"session_name"`
	SessionStartsAt pgtype.Timestamptz `json:"session_starts_at"`
}

func (q *Queries) InsertSession(ctx context.Context, arg InsertSessionParams) (int32, error) {
	row := q.db.QueryRow(ctx, insertSession,
		arg.EventID,
		arg.SessionKind,
		arg.SessionName,
		arg.SessionStartsAt,
	)
	var session_id int32
	err := row.Scan(&session_id)
	return session_id, err
}

const insertTeam = `-- name: InsertTeam :one
INSERT INTO TEAMS (serie_id, team_name, team_external_id)
VALUES ($1, $2, $3)
RETURNING team_id
`

type InsertTeamParams struct {
	SerieID        string      `json:"serie_id"`
	TeamName       string      `json:"team_name"`
	TeamExternalID pgtype.Text `json:"team_external_id"`
}

func (q *Queries) InsertTeam(ctx context.Context, arg InsertTeamParams) (int32, error) {
	row := q.db.QueryRow(ctx, insertTeam, arg.SerieID, arg.TeamName, arg.TeamExternalID)
	var team_id int32
	err := row.Scan(&team_id)
	return team_id, err
}

const updateDriverTeam = `-- name: UpdateDriverTeam :exec
UPDATE DRIVERS
SET team_id = $2
WHERE driver_id = $1
`

type UpdateDriverTeamParams struct {
	DriverID int32       `json:"driver_id"`
	TeamID   pgtype.Int4 `json:"team_id"`
}

func (q *Queries) UpdateDriverTeam(ctx context.Context, arg UpdateDriverTeamParams) error {
	_, err := q.db.Exec(ctx, updateDriverTeam, arg.DriverID, arg.TeamID)
	return err
}

const upsertCircuit = `-- name: UpsertCircuit :one
INSERT INTO CIRCUITS (
    circuit_slug,
    circuit_name,
    circuit_locality,
    circuit_country,
    circuit_latitude,
    circuit_longitude,
    circuit_external_id
) VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (circuit_slug) DO UPDATE SET
    circuit_name = EXCLUDED.circuit_name,
    circuit_locality = EXCLUDED.circuit_locality,
    circuit_country = EXCLUDED.circuit_country,
    circuit_latitude = EXCLUDED.circuit_latitude,
    circuit_longitude = EXCLUDED.circuit_longitude,
    circuit_external_id = COALESCE(EXCLUDED.circuit_external_id, CIRCUITS.circuit_external_id)
RETURNING circuit_id
`

type UpsertCircuitParams struct {
	CircuitSlug       string        `json:"circuit_slug"`
	CircuitName       string        `json:"circuit_name"`
	CircuitLocality   pgtype.Text   `json:"circuit_locality"`
	CircuitCountry    pgtype.Text   `json:"circuit_country"`
	CircuitLatitude   pgtype.Float8 `json:"circuit_latitude"`
	CircuitLongitude  pgtype.Float8 `json:"circuit_longitude"`
	CircuitExternalID pgtype.Text   `json:"circuit_external_id"`
}

func (q *Queries) UpsertCircuit(ctx context.Context, arg UpsertCircuitParams) (int32, error) {
	row := q.db.QueryRow(ctx, upsertCircuit,
		arg.CircuitSlug,
		arg.CircuitName,
		arg.CircuitLocality,
		arg.CircuitCountry,
		arg.CircuitLatitude,
		arg.CircuitLongitude,
		arg.CircuitExternalID,
	)
	var circuit_id int32
	err := row.Scan(&circuit_id)
	return circuit_id, err
}

const upsertEvent = `-- name: UpsertEvent :one
INSERT INTO EVENTS (
    serie_id, circuit_id, event_season, event_round, event_slug,
    event_name, event_starts_at, event_status, event_official_url,
    event_ticket_url, event_external_id
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
ON CONFLICT (serie_id, event_season, event_round) DO UPDATE SET
    circuit_id = EXCLUDED.circuit_id,
    event_slug = EXCLUDED.event_slug,
    event_name = EXCLUDED.event_name,
    event_starts_at = EXCLUDED.event_starts_at,
    event_status = EXCLUDED.event_status,
    event_official_url = EXCLUDED.event_official_url,
    event_ticket_url = EXCLUDED.event_ticket_url,
    event_external_id = EXCLUDED.event_external_id
RETURNING event_id
`

type UpsertEventParams struct {
	SerieID          string             `json:"serie_id"`
	CircuitID        int32              `json:"circuit_id"`
	EventSeason      int32              `json:"event_season"`
	EventRound       int32              `json:"event_round"`
	EventSlug        string             `json:"event_slug"`
	EventName        string             `json:"event_name"`
	EventStartsAt    pgtype.Timestamptz `json:"event_starts_at"`
	EventStatus      string             `json:"event_status"`
	EventOfficialUrl pgtype.Text        `json:"event_official_url"`
	EventTicketUrl   pgtype.Text        `json:"event_ticket_url"`
	EventExternalID  pgtype.Text        `json:"event_external_id"`
}

func (q *Queries) UpsertEvent(ctx context.Context, arg UpsertEventParams) (int32, error) {
	row := q.db.QueryRow(ctx, upsertEvent,
		arg.SerieID,
		arg.CircuitID,
		arg.EventSeason,
		arg.EventRound,
		arg.EventSlug,
		arg.EventName,
		arg.EventStartsAt,
		arg.EventStatus,
		arg.EventOfficialUrl,
		arg.EventTicketUrl,
		arg.EventExternalID,
	)
	var event_id int32
	err := row.Scan(&event_id)
	return event_id, err
}

const upsertResult = `-- name: UpsertResult :exec
INSERT INTO RESULTS (
    event_id, session_type, result_position, driver_id, team_id,
    result_time_or_gap, result_points
) VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (event_id, session_type, result_position) DO UPDATE SET
    driver_id = EXCLUDED.driver_id,
    team_id = EXCLUDED.team_id,
    result_time_or_gap = EXCLUDED.result_time_or_gap,
    result_points = EXCLUDED.result_points
`

type UpsertResultParams struct {
	EventID         int32         `json:"event_id"`
	SessionType     string        `json:"session_type"`
	ResultPosition  int32         `json:"result_position"`
	DriverID        int32         `json:"driver_id"`
	TeamID          int32         `json:"team_id"`
	ResultTimeOrGap pgtype.Text   `json:"result_time_or_gap"`
	ResultPoints    pgtype.Float8 `json:"result_points"`
}

func (q *Queries) UpsertResult(ctx context.Context, arg UpsertResultParams) error {
	_, err := q.db.Exec(ctx, upsertResult,
		arg.EventID,
		arg.SessionType,
		arg.ResultPosition,
		arg.DriverID,
		arg.TeamID,
		arg.ResultTimeOrGap,
		arg.ResultPoints,
	)
	return err
}
